import generateSignature from './services/palmpay.js';
const data = {
  status: true,
  data: {
    AIRTEL: [
      {
        networkId: 2,
        planId: 110,
        name: '100MB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '75.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 111,
        name: '300MB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '150.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 112,
        name: '500MB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '300.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 113,
        name: '1GB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '600.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 114,
        name: '2GB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '1200.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 115,
        name: '5GB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '3000.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 116,
        name: '10GB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '6000.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 117,
        name: '15GB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '9000.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 118,
        name: '20GB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '12000.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 9000,
        name: '150MB [AWOOF]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '50.00',
        ourPrice: '60.00',
        type: 'AWOOF',
      },
      {
        networkId: 2,
        planId: 9001,
        name: '300MB [AWOOF]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: '118.00',
        type: 'AWOOF',
      },
      {
        networkId: 2,
        planId: 9002,
        name: '600MB [AWOOF]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '200.00',
        ourPrice: '250.00',
        type: 'AWOOF',
      },
      {
        networkId: 2,
        planId: 9003,
        name: '1GB [AWOOF]',
        validity: '3 Days',
        currency: 'NGN',
        telcoPrice: '300.00',
        ourPrice: '350.00',
        type: 'AWOOF',
      },
      {
        networkId: 2,
        planId: 9005,
        name: '3GB [AWOOF]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: '1050.00',
        type: 'AWOOF',
      },
      {
        networkId: 2,
        planId: 9006,
        name: '7GB [AWOOF]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '2000.00',
        ourPrice: '2050.00',
        type: 'AWOOF',
      },
      {
        networkId: 2,
        planId: 9007,
        name: '10GB [AWOOF]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '3000.00',
        ourPrice: '3050.00',
        type: 'AWOOF',
      },
      {
        networkId: 2,
        planId: 50001,
        name: 'All Social Daily (Data - 40.0 MB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '50.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50004,
        name: 'Instagram 250MB (Data - 250.0 MB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50005,
        name: 'TikTok (Data - 400.0 MB) [GIFTING]',
        validity: '3 Days',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50006,
        name: 'All Social Weekly (Data - 200.0 MB) [GIFTING]',
        validity: '5 Days',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50007,
        name: '100MB Daily [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50008,
        name: 'Day and Night Bundles (Data - 450.0 MB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '120.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50009,
        name: 'Instagram Bundle 1GB (Data - 1.0 GB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '200.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50010,
        name: '200MB Daily (Get 20% Bonus) (Data - 200.0 MB) (Bonus: 40MB, Valid for a Day) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '200.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50014,
        name: '2GB 2 Days (Data - 2.0 GB) (Bonus: 400MB, Valid for a Day) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50016,
        name: 'YouTube Night - Weekly (1-5AM) (Data - 300.0 MB) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '150.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50018,
        name: 'YouTube Pack Bundle - Weekly (Data - 300.0 MB) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '300.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50024,
        name: 'Axa Health (Data - 1.0 GB) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '700.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50035,
        name: 'Axa Health (Data - 2.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '1700.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50040,
        name: 'Axa Health (Data - 10.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '3500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50045,
        name: '30GB Monthly (Get 20% Bonus) (Data - 30.0 GB) (Bonus: 5GB, Valid for a Month) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '8000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50047,
        name: '40GB Monthly (Get 20% Bonus) (Data - 40.0 GB) (Bonus: 8GB, Valid for a Month) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '10000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50050,
        name: '240GB Monthly (Data - 240.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '30000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50051,
        name: '280GB Monthly (Data - 280.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '36000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50052,
        name: '400GB Quarterly (Data - 400.0 GB) [GIFTING]',
        validity: '90 Days',
        currency: 'NGN',
        telcoPrice: '50000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50055,
        name: 'Unlimited Ultra Router Bundle - 30GB (Data - 30.0 GB) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50056,
        name: 'Airtel Router Plans 18 GB (Data - 18.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50057,
        name: 'Ultra Plans Router only 40GB + 250MB daily (Data - 40.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '10000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50058,
        name: 'Airtel Router Plans 40 GB (Data - 40.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '10000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50059,
        name: 'Ultra Plans Router only 75GB + 250MB daily (Data - 75.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50060,
        name: 'Unlimited Ultra Light - 120GB (Data - 120.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50061,
        name: 'Airtel Router Plans 75 GB (Data - 75.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50062,
        name: 'Airtel Router Plans 120 GB (Data - 120.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50063,
        name: 'Unlimited 20 30Days (Data - 20.0 MBPS) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50064,
        name: 'Ultra Plans Router only 120GB + 3GB daily (Data - 120.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50065,
        name: 'Unlimited Ultra standard - 200GB (Data - 200.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50066,
        name: 'New Customer Bundle 25k (Data - 20.0 MBPS) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '25000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50067,
        name: 'Unlimited Ultra Diamond - 300GB (Data - 300.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '30000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50068,
        name: 'Unlimited 40 30Days (Data - 40.0 MBPS) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '35000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50069,
        name: 'Unlimited 60 30Days (Data - 60.0 MBPS) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '50000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50070,
        name: 'Unlimited 20 90Days (Data - 20.0 MBPS) [GIFTING]',
        validity: '90 Days',
        currency: 'NGN',
        telcoPrice: '60000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50071,
        name: 'Unlimited Ultra Platinum - 550GB (Data - 550.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '60000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50072,
        name: 'Unlimited 40 90Days (Data - 40.0 MBPS) [GIFTING]',
        validity: '90 Days',
        currency: 'NGN',
        telcoPrice: '105000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50073,
        name: 'Unlimited 20 180Days (Data - 20.0 MBPS) [GIFTING]',
        validity: '180 Days',
        currency: 'NGN',
        telcoPrice: '120000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50074,
        name: 'Unlimited 60 90Days (60.0 MBPS) [GIFTING]',
        validity: '90 Days',
        currency: 'NGN',
        telcoPrice: '150000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50075,
        name: 'Unlimited 40 180Days (Data - 40.0 MBPS) [GIFTING]',
        validity: '180 Days',
        currency: 'NGN',
        telcoPrice: '210000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50076,
        name: 'Unlimited 20 360Days (Data - 20.0 MBPS) [GIFTING]',
        validity: '1 Year',
        currency: 'NGN',
        telcoPrice: '240000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50077,
        name: 'Unlimited 60 180Days (Data - 60.0 MBPS) [GIFTING]',
        validity: '180 Days',
        currency: 'NGN',
        telcoPrice: '300000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50078,
        name: 'Unlimited 40 360Days (Data - 40.0 MBPS) [GIFTING]',
        validity: '1 Year',
        currency: 'NGN',
        telcoPrice: '420000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50079,
        name: 'Unlimited 60 360Days (Data - 60.0 MBPS) [GIFTING]',
        validity: '1 Year',
        currency: 'NGN',
        telcoPrice: '600000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50080,
        name: 'Data++ (More Data) 2.5 GB (Data - 2.5 GB) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50081,
        name: 'Data++ (More Data) 11 GB (Data - 11.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '3000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50082,
        name: 'Data++ (More Data) 15 GB (Data - 15.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '4000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50083,
        name: 'Data++ (More Data) 22 GB (Data - 22.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50085,
        name: 'All Social Monthly (Data - 700.0 MB) [GIFTING]',
        validity: '25 Days',
        currency: 'NGN',
        telcoPrice: '300.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50089,
        name: '6X (Voice - 1200 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '200.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50090,
        name: '6X (Voice - 1800 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '300.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50091,
        name: '6X (Voice - 3000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50092,
        name: '6X (Voice - 6000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50093,
        name: 'Talk More N100 (Voice - 500 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50094,
        name: 'Talk More N150 (Voice - 750 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '150.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50095,
        name: 'Talk More N200 (Voice - 1000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '200.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50096,
        name: 'Talk More N250 (Voice - 1250 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '250.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50097,
        name: 'Talk More N300 (Voice - 1500 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '300.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50098,
        name: 'Talk More N500 (Voice - 2500 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50099,
        name: 'Talk More N1000 (Voice - 5000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50100,
        name: 'Talk More N1500 (Voice - 7500 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '1500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50101,
        name: 'Talk More N3000 (Voice - 15000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '3000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50103,
        name: 'Talkmore Plus (Data) N500 (Data - 750.0 MB, Voice - 1000 Naira) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50104,
        name: 'Talkmore Plus (Voice +) N500 (Voice - 2500 Naira) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50105,
        name: 'Talkmore Plus (Voice +) N1000 (Voice - 5000 Naira) [GIFTING]',
        validity: '14 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50106,
        name: 'Talkmore Plus (Data) N2000 (Data - 4.5 GB, Voice - 4000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '2000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50107,
        name: 'Talkmore Plus (Voice +) N2000 (Voice - 10000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '2000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50108,
        name: 'Talkmore Plus (Data) N5000 (Data - 15.0 GB, Voice - 10000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50109,
        name: 'Talkmore Plus (Voice +) N5000 (Voice - 25000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50110,
        name: 'Talkmore Plus (Voice +) N10000 (Voice - 50000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '10000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50111,
        name: 'Talkmore Plus (Voice +) N15000 (Voice - 75000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50112,
        name: 'Talkmore Plus (Voice +) N20000 (Voice - 100000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50113,
        name: 'Talkmore Plus (Data) N1000 (Data - 1.5 GB, Voice - 2000 Naira) [GIFTING]',
        validity: '14 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50114,
        name: 'Talkmore Plus (Data) N10000 (Data - 30.0 GB, Voice - 20000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '10000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50115,
        name: 'Talkmore Plus (Data+) N15000 (Data - 50.0 GB, Voice - 35000 Naira) [GIFTING]',
        validity: '90 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50116,
        name: 'Talkmore Plus (Data) N20000 (Data - 70.0 GB, Voice - 45000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50117,
        name: 'Roam And Browse 100 MB (Data - 100.0 MB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50118,
        name: 'Roam And Browse 500 MB (Data - 500.0 MB) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50119,
        name: 'Roam Like Home 1 GB (Data - 1.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '2000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50120,
        name: 'N10,000 Roaming Bundle (Voice - 10000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '10000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50121,
        name: 'N15,000 Roaming Bundle (Voice - 15000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50122,
        name: 'N20,000 Roaming Bundle (Voice - 20000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50123,
        name: 'Roam And Browse 1 GB (Data - 1.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '30000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50124,
        name: 'N50,000 Roaming Bundle (Voice - 50000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '50000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50125,
        name: 'Roam And Browse 3 GB (Data - 3.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '80000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50126,
        name: 'N100,000 Roaming Bundle (Voice - 100000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '100000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50127,
        name: 'Roam Like Home 400 MB (Data - 400.0 MB) [GIFTING]',
        validity: '15 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 9012,
        name: '2GB [AWOOF]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: '550.00',
        type: 'AWOOF',
      },
      {
        networkId: 2,
        planId: 119,
        name: '200MB [CG]',
        validity: '3 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '125.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 120,
        name: '3GB [CG]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '0.00',
        ourPrice: '1800.00',
        type: 'CG',
      },
      {
        networkId: 2,
        planId: 50128,
        name: 'Night Plan 50 (Data - 250.0 MB) 12 Midnight - 5am [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '50.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50129,
        name: 'Daily Plan 75 (Data - 75.0 MB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '75.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50130,
        name: 'Daily Plan 100 (Data - 100.0 MB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50131,
        name: 'Social Plan 100 (Data - 200.0 MB) (Whatsapp, Facebook, Instagram, Youtube and Tiktok) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50132,
        name: 'Daily Plan 200 (Data - 200.0 MB) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '200.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50133,
        name: 'Daily Plan 300 (Data - 300.0 MB) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '300.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50135,
        name: 'Binge 500 (Data - 1.0 GB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50136,
        name: 'Binge 600 (Data - 1.5 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '600.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50137,
        name: 'Binge 750 (Data - 2.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '750.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50138,
        name: 'Binge 1000 (Data - 3.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50139,
        name: 'Binge 1500 (Data - 5.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '2 Days',
        currency: 'NGN',
        telcoPrice: '1500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50140,
        name: 'Weekly Plan 500 (Data - 500.0 MB) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50141,
        name: 'Social Plan 500 (Data - 1.5 GB) (Whatsapp, Facebook, Instagram, Youtube and Tiktok) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50142,
        name: 'Weekly Plan 800 (Data - 1.0 GB) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '800.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50143,
        name: 'Weekly Plan 1000 (Data - 1.5 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50144,
        name: 'Weekly Plan 1500 (Data - 3.5 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '1500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50145,
        name: 'Weekly Plan 2500 (Data - 6.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '2500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50146,
        name: 'Weekly Plan 3000 (Data - 10.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '3000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50147,
        name: 'Weekly Plan 5000 (Data - 18.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50148,
        name: 'Monthly Plan 1500 (Data - 2.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '1500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50149,
        name: 'Monthly Plan 2000 (Data - 3.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '2000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50150,
        name: 'Monthly Plan 2500 (Data - 4.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '2500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50151,
        name: 'Monthly Plan 3000 (Data - 8.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '3000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50152,
        name: 'Monthly Plan 4000 (Data - 10.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '4000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50153,
        name: 'Monthly Plan 5000 (Data - 13.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50154,
        name: 'Monthly Plan 6000 (Data - 18.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '6000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50155,
        name: 'Monthly Plan 8000 (Data - 25.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '8000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50156,
        name: 'Monthly Plan 10000 (Data - 35.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '10000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50157,
        name: 'Monthly Plan 15000 (Data - 60.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50158,
        name: 'Monthly Plan 20000 (Data - 100.0 GB) Bonus: 2GB Youtube Night + 200MB (YT, IG & Tiktok) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50159,
        name: 'Monthly Plan 30000 (Data - 160.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '30000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50160,
        name: 'Monthly Plan 40000 (Data - 210.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '40000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50161,
        name: 'Monthly Plan 50000 (Data - 300.0 GB) [GIFTING]',
        validity: '90 Days',
        currency: 'NGN',
        telcoPrice: '50000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50162,
        name: 'Monthly Plan 60000 (Data - 350.0 GB) [GIFTING]',
        validity: '120 Days',
        currency: 'NGN',
        telcoPrice: '60000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50163,
        name: 'Monthly plan 100000 (Data - 650.0 GB) [GIFTING]',
        validity: '1 Year',
        currency: 'NGN',
        telcoPrice: '100000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50164,
        name: 'Talk More N100 (Voice - 10 Minutes) [GIFTING]',
        validity: '3 Days',
        currency: 'NGN',
        telcoPrice: '100.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50165,
        name: 'Talk More N200 (Voice - 20 Minutes) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '200.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50166,
        name: 'Talk More N300 (Voice - 30 Minutes) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '300.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50167,
        name: 'Talk More N500 (Voice - 50 Minutes) [GIFTING]',
        validity: '14 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50168,
        name: 'Talk More N1000 (Voice - 100 Minutes) [GIFTING]',
        validity: '14 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50169,
        name: 'Talk More N1500 (Voice - 150 Minutes) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '1500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50170,
        name: 'Flexi 500 (Data - 400.0 MB, Voice - 10 Minutes, SMS - 5) (10 mins + 400MB + 5 SMS ) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '500.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50171,
        name: 'Flexi 1000 (Data - 1.2 GB, Voice - 20 Minutes, SMS - 5) (20 mins + 1.2GB + 5 SMS ) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50172,
        name: 'Flexi 2000 (Data - 2.5 GB, Voice - 40 Minutes, SMS - 5) (40 mins + 2.5GB + 5 SMS ) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '2000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50173,
        name: 'Flexi 5000 (Data - 12.0 GB, Voice - 100 Minutes, SMS - 5) (100 mins + 12GB + 5 SMS ) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50174,
        name: 'RoamTheWorld(Data 100MB) N5000 (Data - 100.0 MB) [GIFTING]',
        validity: '1 Day',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50175,
        name: 'RoamTheWorld(Voice) N5000 (Voice - 5000 Naira) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '5000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50176,
        name: 'RoamTheWorld(Data 1GB) N9000 (Data - 1.0 GB) [GIFTING]',
        validity: '7 Days',
        currency: 'NGN',
        telcoPrice: '9000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50177,
        name: 'RoamOneAirtel(Data 1GB) N2000 (Data - 1.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '2000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50178,
        name: 'RoamTheWorld(Voice) N10000 (Voice - 10000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '10000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50179,
        name: 'RoamTheWorld(Voice) N15000 (Voice - 15000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '15000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50180,
        name: 'RoamTheWorld(Voice) N20000 (Voice - 20000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '20000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50181,
        name: 'RoamTheWorld(Data 3GB) N25000 (Data - 1.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '30000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50182,
        name: 'RoamTheWorld(Data 5GB) N40000 (Data - 5.0 GB) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '40000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50183,
        name: 'RoamTheWorld(Voice) N50000 (Voice - 50000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '50000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50184,
        name: 'RoamTheWorld(Voice) N100000 (Voice - 100000 Naira) [GIFTING]',
        validity: '30 Days',
        currency: 'NGN',
        telcoPrice: '100000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
      {
        networkId: 2,
        planId: 50185,
        name: 'RoamOneAirtel(Data 400MB) N1000 (Data - 400.0 MB) [GIFTING]',
        validity: '15 Days',
        currency: 'NGN',
        telcoPrice: '1000.00',
        ourPrice: null,
        type: 'GIFTING',
      },
    ],
  },
};

const signature = generateSignature({
  virtualAccountName: 'john doe',
  identityType: 'BVN',
  licenseNumber: 'RC12345',
  email: 'hello@johndoe.com',
  customerName: 'john doe',
  accountReference: 'ACC_VIR_JOHN_923847',
});

console.log(signature);
